name: 'Install Rundown'
description: 'Installs rundown'
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: install.sh
      shell: bash
